<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CS0618;CS0108</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>.\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>.\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>.\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
